germany.txt

FDA-2079 - allow data privacy notification on onmeda.de

FDA-2079 - allow notification on onmeda

---

germany.txt

Allow images on gofeminin.de as they are part of the content.

FDA-2084 - Allow images on gofeminin

---

germany.txt

FDA-2084 deleted filter for gofeminin.de as it was added to [ELGermany](https://github.com/easylist/easylistgermany/commit/e5f3e99706f81b39f8cfc75b6177b820d79e0f79)

D: FDA-2084

---

germany.txt

FDA-2102 - allow cookie consent message on ladenzeile.de

A: FDA-2102 allow cookie consent for ladenzeile.de

---

germany.txt

FDA-2116 - allow selfpromo message on manager-magazin.de

A: FDA-2116 - allow selfpromo message on manager-magazin.de

---

germany.txt

Delete filter: `@@||de.lzstatic.com/js/*/gdpr/$script,domain=ladenzeile.de
` for ladenzeile.de since [filters](https://github.com/easylist/easylist/commit/a79a495ee09b7d8c7ff251dcd0fe83209eb3bdd4) added by FLA work.

D: FDA-2102

---

germany.txt

D: FDA-2116 - Deleted rule for manager-magazin.de since Khrin [removed filter](https://github.com/easylist/easylist/commit/df6b363) that was causing issue.

D: FDA-2116

---

germany.txt

FDA-2145 - adds allowing filter for finanzen.ch

A: FDA-2145

---

germany.txt

Deleting allowing filter since Fanboy [adjusted filter](https://github.com/easylist/easylist/commit/1b4e8eda6600a72622dfad8864596f02eeeda687) on Easy Privacy

D: FDA-2145

---

germany.txt

Allow push notification on ran.de
FDA-2302
```
@@||aswpsdkus.com/notify/*/ua-html-prompt.min.js$domain=ran.de
@@||aswpsdkus.com/notify/*/ua-sdk.min.js$domain=ran.de
```

A: FDA-2302

---

germany.txt

FDA-2366 and FDA-2367
Allow push notification on finanzen `@@||googletagmanager.com/gtm.js$script,domain=finanzen.ch|finanzen.net|finanzen.at`

A: FDA-2366 and FDA-2367

---

germany.txt

Allow content on https://www.travelbook.de/orte/lost-places/villa-epecuen
Easy Privacy rule: `||taboola.com^*/json?tim=` blocks the content.

A: FDA-2572

---

germany.txt

Allow videos on [gamestar.de](https://www.gamestar.de/videos/endlich-next-gen-grafik-die-schoensten-spiele-2022,104397.html) blocked by EL rule: `||getjad.io^`

A: FDA-2665

---

germany.txt

Allow **trustedshops** logo on https://www.lesershop24.de/auto-bild/probeabo/?utm_medium=Content&utm_source=autobild.de&utm_content=Textlink+10164393+BQ00ABC214A01SZ&utm_campaign=AUTO+BILD+Abo
EasyPrivacy rule blocks image and script: `||widgets.trustedshops.com^$third-party`

A: FDA-2671

---

germany.txt

Allow feedback button on https://www.idealo.de/preisvergleich/OffersOfProduct/201589508_-m-574-winter-workwear-black-new-balance.html

A: FDA-2672

---

germany.txt

Allow survey on https://www.idealo.at/preisvergleich/OffersOfProduct/200637075_-xbox-series-s-microsoft.html blocked by Easy Privacy rules:
```
||googletagmanager.com^
||siteintercept.qualtrics.com^$third-party
```

A: FDA-2675

---

germany.txt

Allow WETTERUPDATE on https://www.wetter.com/

A: FDA-2674

---

germany.txt

Allow missing content on https://11freunde.de/startseite

A: FDA-2755

---

germany.txt

Deleted [rules](https://github.com/abp-filters/abp-filters-compliance/commit/4ce0826) from ithe ABP compliance list as they were added to EL Germany: https://github.com/easylist/easylistgermany/commit/f00c9a5

D: FDA-2755

---

germany.txt

Allow videos at https://www.vip.de/cms/emma-schweigers-flucht-nach-amerika-erstmals-spricht-mama-dana-darueber-4932227.html
Rules blocking the video are in Easyprivacy
`||technical-service.net^$third-party`
`/ipdvdc/*`

A: FDA-2824

---

germany.txt

Forgot to add a comment ! to existing rule for gruenderszene.de just in case domain is back.
**Let me know if is better to delete rule instead.**
Reference commit: https://github.com/abp-filters/abp-filters-compliance/pull/39

M: fixes for gruenderszene.de

---

germany.txt

Allow video blocked on https://www.auto-motor-und-sport.de/neuheiten/bmw-m3-touring-2022-alle-infos-und-fotos-zum-power-kombi/
EasyPrivacy rules causing the issue:
`/metaTag.min.js`
`||mps-gba.de^$third-party`

A: FDA-2963

---

germany.txt

Allow content blocked on https://www.wetter.de/

A: FDA-2966

---

germany.txt

Allow missing content on http://www.autobild.de/

A: FD-3083

---

germany.txt

Delete [fixes](https://github.com/abp-filters/abp-filters-compliance/commit/cb12f00) for **autobild.de**
Filter causing the issue has been [adjusted](https://github.com/easylist/easylistgermany/commit/0a99ba0) in EL Germany.

D: FD-3133

---

germany.txt

Refer to: https://github.com/easylist/easylist/pull/13352 (filter not added by filter list author)

A: FD-3245

---

germany.txt

video contend from the page is not loading with ABP enabled

A: FD-3452

---

germany.txt

Push notification is being blocked by the Premium List.

A: FD-3504

---

germany.txt

Unable to view video content on `https://www.testbild.de/`

A: FD-3512

---

germany.txt

Filters added in the specific allowlists

D: FD-3521

---

germany.txt

Broken layout at https://www.jetzt.de/

A: FD-3640

---

germany.txt

D: FD-3640

---

germany.txt

A: FD-3707

---

germany.txt

Easy Privacy breaking search functionality

M: FD-3741

---

germany.txt

Allow comment section missing at https://www.handelsblatt.com/

A: FD-3819

---

germany.txt

R: FD-3819

---

germany.txt

Allow blocked content at https://www.onvista.de/anlagethemen?referrer=https%3A%2F%2Fmail.google.com%2F&referrer=https%3A%2F%2Fjira.eyeo.com%2F

A: FD-3938

---

germany.txt

Allow cookies/privacy consent blocked on https://www.onmeda.de/

A: FD-4028

---

germany.txt

Allow Cookie consent messages at https://www.idealo.co.uk/

A: FD-4031

---

germany.txt

R: FD-4424

---

germany.txt

For IDC about cookies both filters are necessary.  For Premium list only @@||consentmanager.net^$third-party

A: FD-5394

---

germany.txt

Fixed at https://github.com/easylist/easylist/pull/18800/files

R: FD-5385 | FD-5386 | FD-5389 | FD-5390 | FD-5393

---

germany.txt

https://github.com/easylist/easylistgermany/commit/853e4e6067e3899de96fa038599ad4332e18fde2

R: FD-5384

---

germany.txt

R: FD-6116
